# ---------- Setup output Directories -------------------------
FUNCTION ( SET_PROJECT_RUNTIME_OUTPUT_DIR dir )
  SET ( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${dir} CACHE PATH "Single Directory for all Executables." )
ENDFUNCTION ( SET_PROJECT_RUNTIME_OUTPUT_DIR )

FUNCTION ( SET_PROJECT_ARCHIVE_OUTPUT_DIR dir )
  SET ( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${dir} CACHE PATH "Single Directory for all static libraries." )
ENDFUNCTION ( SET_PROJECT_ARCHIVE_OUTPUT_DIR )

FUNCTION ( SET_PROJECT_LIBRARY_OUTPUT_DIR dir )
  SET ( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${dir} CACHE PATH "Single Directory for all Libraries" )
ENDFUNCTION ( SET_PROJECT_LIBRARY_OUTPUT_DIR )

FUNCTION ( SET_PROJECT_OUTPUT_DIR dir )
  SET_PROJECT_RUNTIME_OUTPUT_DIR ( ${dir} )
  SET_PROJECT_ARCHIVE_OUTPUT_DIR ( ${dir} )
  SET_PROJECT_LIBRARY_OUTPUT_DIR ( ${dir} )
ENDFUNCTION ( SET_PROJECT_OUTPUT_DIR )

# --------- Setup Target output Directory -------------
FUNCTION ( SET_TARGET_RUNTIME_OUTPUT_DIR target dir )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${dir}" )
ENDFUNCTION ( SET_TARGET_RUNTIME_OUTPUT_DIR )

FUNCTION ( SET_TARGET_ARCHIVE_OUTPUT_DIR target dir )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "${dir}" )
ENDFUNCTION ( SET_TARGET_ARCHIVE_OUTPUT_DIR )

FUNCTION ( SET_TARGET_LIBRARY_OUTPUT_DIR target dir )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "${dir}" )
  SET_TARGET_PROPERTIES ( ${target} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${dir}" )
ENDFUNCTION ( SET_TARGET_LIBRARY_OUTPUT_DIR )

FUNCTION ( SET_TARGET_OUTPUT_DIR target dir )
  SET_TARGET_RUNTIME_OUTPUT_DIR ( ${target} ${dir} )
  SET_TARGET_ARCHIVE_OUTPUT_DIR ( ${target} ${dir} )
  SET_TARGET_LIBRARY_OUTPUT_DIR ( ${target} ${dir} )
ENDFUNCTION ( SET_TARGET_OUTPUT_DIR )
